import HorizontalNav from '@/components/Navbar/HorizontalNav';
import './globals.css';
import { Inter } from 'next/font/google';
import SideNav from '@/components/Navbar/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        {/* Main  Navbar*/}
        <div className="main-navbar">
          {/* Sidebar  Navbar*/}

          <div className=" side-navbar">
            <SideNav />
          </div>
          {/* Horizontal  Navbar*/}

          <div className="horizontal-navbar">
            <HorizontalNav />
          </div>
          </div>
        {/* Body Section*/}

        <div className="body-child-pass">{children}</div>
        {/* Body Section*/}
      </body>
    </html>
  );
}
